In [1]:
import pandas as pd

In [2]:
record1 = pd.Series({'Name': 'Alice',
                        'Class': 'Physics',
                        'Score': 85})
record2 = pd.Series({'Name': 'Jack',
                        'Class': 'Chemistry',
                        'Score': 82})
record3 = pd.Series({'Name': 'Helen',
                        'Class': 'Biology',
                        'Score': 90})

In [7]:
df =pd.DataFrame([record1,record2,record3],
                 index=["school1","school2","school3"])
df

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school3  Helen    Biology     90

In [18]:
students = [{'Name': 'Alice',
              'Class': 'Physics',
              'Score': 85},
            {'Name': 'Jack',
             'Class': 'Chemistry',
             'Score': 82},
            {'Name': 'Helen',
             'Class': 'Biology',
             'Score': 90}]

df =pd.DataFrame(students,index=["school1","school2","school1"])
df

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [19]:
df.loc["school2"]

Name          Jack
Class    Chemistry
Score           82
Name: school2, dtype: object

In [20]:
type(df.loc["school2"])

pandas.core.series.Series

In [23]:
df.loc["school1"]

          Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     90

In [22]:
type(df.loc["school1"])

pandas.core.frame.DataFrame

In [26]:
df.loc["school1","Name"]

school1    Alice
school1    Helen
Name: Name, dtype: object

In [27]:
df.T

       school1    school2  school1
Name     Alice       Jack    Helen
Class  Physics  Chemistry  Biology
Score       85         82       90

In [28]:
df.T.loc["Name"]

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [29]:
df["Name"]

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [30]:
df.loc["Name"]

KeyError: 'Name'

In [31]:
df.loc["school1"]["Name"]

school1    Alice
school1    Helen
Name: Name, dtype: object

In [33]:
print(type(df.loc['school1'])) 
print(type(df.loc['school1']['Name']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [36]:
df.loc[:,["Name","Score"]]

          Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

In [37]:
df.drop("school1")

         Name      Class  Score
school2  Jack  Chemistry     82

In [38]:
df

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [40]:
copy_df =df.copy()
copy_df.drop("Name",inplace=True,axis=1)

In [41]:
copy_df

             Class  Score
school1    Physics     85
school2  Chemistry     82
school1    Biology     90

In [42]:
del copy_df["Class"]
copy_df

         Score
school1     85
school2     82
school1     90

In [43]:
df["Classranking"] =None

In [44]:
df

          Name      Class  Score Classranking
school1  Alice    Physics     85         None
school2   Jack  Chemistry     82         None
school1  Helen    Biology     90         None