In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.DataFrame(np.random.rand(9,4),index=list("abcdefghi"), columns=list("ABCD"))

In [3]:
df.shape

(9, 4)

In [4]:
df

          A         B         C         D
a  0.420508  0.369232  0.481874  0.460519
b  0.836080  0.095927  0.440742  0.655417
c  0.585459  0.433891  0.715075  0.361898
d  0.202699  0.481832  0.915493  0.425269
e  0.809615  0.421426  0.046512  0.070518
f  0.019384  0.963409  0.290034  0.927531
g  0.539567  0.719234  0.077633  0.739678
h  0.308638  0.621499  0.565439  0.699207
i  0.455048  0.025915  0.339744  0.388680

In [5]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, a to i
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       9 non-null      float64
 1   B       9 non-null      float64
 2   C       9 non-null      float64
 3   D       9 non-null      float64
dtypes: float64(4)
memory usage: 660.0+ bytes

In [7]:
df.head()

          A         B         C         D
a  0.420508  0.369232  0.481874  0.460519
b  0.836080  0.095927  0.440742  0.655417
c  0.585459  0.433891  0.715075  0.361898
d  0.202699  0.481832  0.915493  0.425269
e  0.809615  0.421426  0.046512  0.070518

In [11]:
another_df =pd.DataFrame(
    np.random.rand(100,4),
    index=range(100),
    columns=list("ABCD"))

In [14]:
another_df.head()

          A         B         C         D
0  0.798475  0.563940  0.912618  0.817245
1  0.503050  0.960696  0.038275  0.388787
2  0.945268  0.605036  0.416977  0.465573
3  0.183054  0.702669  0.023455  0.542592
4  0.632538  0.123198  0.101756  0.749302

In [15]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='object')

In [17]:
df.loc["a"]

A    0.420508
B    0.369232
C    0.481874
D    0.460519
Name: a, dtype: float64

In [26]:
df.loc['a', 'B':'D']

B    0.369232
C    0.481874
D    0.460519
Name: a, dtype: float64

In [25]:
df.loc['a':'d', :]

          A         B         C         D
a  0.420508  0.369232  0.481874  0.460519
b  0.836080  0.095927  0.440742  0.655417
c  0.585459  0.433891  0.715075  0.361898
d  0.202699  0.481832  0.915493  0.425269

In [ ]:
df.iloc[0:4,:]

          A         B         C         D
a  0.420508  0.369232  0.481874  0.460519
b  0.836080  0.095927  0.440742  0.655417
c  0.585459  0.433891  0.715075  0.361898
d  0.202699  0.481832  0.915493  0.425269

In [28]:
df.iloc[0 ,1:4]

B    0.369232
C    0.481874
D    0.460519
Name: a, dtype: float64

In [29]:
df.iloc[:,1]

a    0.369232
b    0.095927
c    0.433891
d    0.481832
e    0.421426
f    0.963409
g    0.719234
h    0.621499
i    0.025915
Name: B, dtype: float64

In [40]:
selector =lambda df : df["A"] > 0.5

In [39]:
df.loc[selector]

          A         B         C         D
b  0.836080  0.095927  0.440742  0.655417
c  0.585459  0.433891  0.715075  0.361898
e  0.809615  0.421426  0.046512  0.070518
g  0.539567  0.719234  0.077633  0.739678

In [48]:
selector = lambda df: (df['A'] > 0.5)&(df['B'] < 0.2)

In [49]:
df.loc[selector]

         A         B         C         D
b  0.83608  0.095927  0.440742  0.655417

In [50]:
condition_for_selection = (df['A'] > 0.5)&(df['B'] < 0.2)

In [51]:
condition_for_selection

a    False
b     True
c    False
d    False
e    False
f    False
g    False
h    False
i    False
dtype: bool

In [52]:
df.loc[(df['A'] > 0.5)&(df['B'] < 0.2)]

         A         B         C         D
b  0.83608  0.095927  0.440742  0.655417

OR operator : | 
NOT operator :~

In [53]:
condition_for_selection = (df['A'] > 0.5) | ~(df['B'] < 0.2)

In [54]:
condition_for_selection

a     True
b     True
c     True
d     True
e     True
f     True
g     True
h     True
i    False
dtype: bool