##### Adding a column in the DataFrame

In [430]:
import pandas as pd
import numpy as np

In [431]:
df =pd.DataFrame(np.random.rand(9,4),index=list("abcdefghi"),columns=list("ABCD"))

In [432]:
df.head()

          A         B         C         D
a  0.897615  0.458515  0.918921  0.259367
b  0.404996  0.489543  0.719259  0.391869
c  0.202180  0.036154  0.457360  0.535389
d  0.847829  0.057048  0.914986  0.625122
e  0.954197  0.168059  0.364463  0.153924

In [433]:
## adding a column
df["E"]=df["A"]* 100

In [434]:
df.head()

          A         B         C         D          E
a  0.897615  0.458515  0.918921  0.259367  89.761497
b  0.404996  0.489543  0.719259  0.391869  40.499620
c  0.202180  0.036154  0.457360  0.535389  20.217969
d  0.847829  0.057048  0.914986  0.625122  84.782889
e  0.954197  0.168059  0.364463  0.153924  95.419671

In [435]:
df["F"] =df["A"] + df["C"]

In [436]:
df.head()

          A         B         C         D          E         F
a  0.897615  0.458515  0.918921  0.259367  89.761497  1.816536
b  0.404996  0.489543  0.719259  0.391869  40.499620  1.124255
c  0.202180  0.036154  0.457360  0.535389  20.217969  0.659540
d  0.847829  0.057048  0.914986  0.625122  84.782889  1.762815
e  0.954197  0.168059  0.364463  0.153924  95.419671  1.318660

In [437]:
criteria =df["A"] < 0.2

In [438]:
criteria

a    False
b    False
c    False
d    False
e    False
f    False
g    False
h     True
i    False
Name: A, dtype: bool

In [439]:
df.loc[criteria,"A"] =0

In [440]:
df

          A         B         C         D          E         F
a  0.897615  0.458515  0.918921  0.259367  89.761497  1.816536
b  0.404996  0.489543  0.719259  0.391869  40.499620  1.124255
c  0.202180  0.036154  0.457360  0.535389  20.217969  0.659540
d  0.847829  0.057048  0.914986  0.625122  84.782889  1.762815
e  0.954197  0.168059  0.364463  0.153924  95.419671  1.318660
f  0.454947  0.104159  0.427967  0.338639  45.494690  0.882914
g  0.464129  0.183931  0.733576  0.975621  46.412931  1.197706
h  0.000000  0.202819  0.443558  0.160414   9.755311  0.541111
i  0.683309  0.504838  0.434979  0.332304  68.330887  1.118288

In [441]:
cities =["mumbai","Delhi","Chennai",
         "Kolkata","Bengalure","Hydrabad",
         "Pune","Ahmedabad","Indore"]

In [442]:
df["city"] =cities

In [443]:
df

          A         B         C         D          E         F       city
a  0.897615  0.458515  0.918921  0.259367  89.761497  1.816536     mumbai
b  0.404996  0.489543  0.719259  0.391869  40.499620  1.124255      Delhi
c  0.202180  0.036154  0.457360  0.535389  20.217969  0.659540    Chennai
d  0.847829  0.057048  0.914986  0.625122  84.782889  1.762815    Kolkata
e  0.954197  0.168059  0.364463  0.153924  95.419671  1.318660  Bengalure
f  0.454947  0.104159  0.427967  0.338639  45.494690  0.882914   Hydrabad
g  0.464129  0.183931  0.733576  0.975621  46.412931  1.197706       Pune
h  0.000000  0.202819  0.443558  0.160414   9.755311  0.541111  Ahmedabad
i  0.683309  0.504838  0.434979  0.332304  68.330887  1.118288     Indore

In [444]:
df_copy= df.copy()

In [445]:
df_copy

          A         B         C         D          E         F       city
a  0.897615  0.458515  0.918921  0.259367  89.761497  1.816536     mumbai
b  0.404996  0.489543  0.719259  0.391869  40.499620  1.124255      Delhi
c  0.202180  0.036154  0.457360  0.535389  20.217969  0.659540    Chennai
d  0.847829  0.057048  0.914986  0.625122  84.782889  1.762815    Kolkata
e  0.954197  0.168059  0.364463  0.153924  95.419671  1.318660  Bengalure
f  0.454947  0.104159  0.427967  0.338639  45.494690  0.882914   Hydrabad
g  0.464129  0.183931  0.733576  0.975621  46.412931  1.197706       Pune
h  0.000000  0.202819  0.443558  0.160414   9.755311  0.541111  Ahmedabad
i  0.683309  0.504838  0.434979  0.332304  68.330887  1.118288     Indore

In [446]:
cities_new=["mumbai","Delhi","Chennai",
        "Kolkata","Bengalure","Hydrabad",
        "Pune","Ahmedabad","Guwahati"]

In [447]:
df_copy["new_city"] =cities_new

In [448]:
df_copy

,A,B,C,D,E,F,city,new_city
a,0.897615,0.458515,0.918921,0.259367,89.761497,1.816536,mumbai,mumbai
b,0.404996,0.489543,0.719259,0.391869,40.499620,1.124255,Delhi,Delhi
c,0.202180,0.036154,0.457360,0.535389,20.217969,0.659540,Chennai,Chennai
d,0.847829,0.057048,0.914986,0.625122,84.782889,1.762815,Kolkata,Kolkata
e,0.954197,0.168059,0.364463,0.153924,95.419671,1.318660,Bengalure,Bengalure
f,0.454947,0.104159,0.427967,0.338639,45.494690,0.882914,Hydrabad,Hydrabad
g,0.464129,0.183931,0.733576,0.975621,46.412931,1.197706,Pune,Pune
h,0.000000,0.202819,0.443558,0.160414,9.755311,0.541111,Ahmedabad,Ahmedabad
i,0.683309,0.504838,0.434979,0.332304,68.330887,1.118288,Indore,Guwahati

In [449]:
criteria =df_copy["city"].isin(["Pune","Bengaluru","Hydrabad"])

In [450]:
criteria

a    False
b    False
c    False
d    False
e    False
f     True
g     True
h    False
i    False
Name: city, dtype: bool

In [451]:
df_copy[df.city=="Bengalure"]

,A,B,C,D,E,F,city,new_city
e,0.954197,0.168059,0.364463,0.153924,95.419671,1.31866,Bengalure,Bengalure

In [452]:
df_copy.loc[df.city=="Bengalure",["city","new_city"]] ="Bengaluru"

In [453]:
df_copy

,A,B,C,D,E,F,city,new_city
a,0.897615,0.458515,0.918921,0.259367,89.761497,1.816536,mumbai,mumbai
b,0.404996,0.489543,0.719259,0.391869,40.499620,1.124255,Delhi,Delhi
c,0.202180,0.036154,0.457360,0.535389,20.217969,0.659540,Chennai,Chennai
d,0.847829,0.057048,0.914986,0.625122,84.782889,1.762815,Kolkata,Kolkata
e,0.954197,0.168059,0.364463,0.153924,95.419671,1.318660,Bengaluru,Bengaluru
f,0.454947,0.104159,0.427967,0.338639,45.494690,0.882914,Hydrabad,Hydrabad
g,0.464129,0.183931,0.733576,0.975621,46.412931,1.197706,Pune,Pune
h,0.000000,0.202819,0.443558,0.160414,9.755311,0.541111,Ahmedabad,Ahmedabad
i,0.683309,0.504838,0.434979,0.332304,68.330887,1.118288,Indore,Guwahati

In [454]:
df_copy.loc[df.city=="Bengalure",["city","new_cities"]] ="Bengaluru"

In [455]:
df_copy

,A,B,C,D,E,F,city,new_city,new_cities
a,0.897615,0.458515,0.918921,0.259367,89.761497,1.816536,mumbai,mumbai,NaN
b,0.404996,0.489543,0.719259,0.391869,40.499620,1.124255,Delhi,Delhi,NaN
c,0.202180,0.036154,0.457360,0.535389,20.217969,0.659540,Chennai,Chennai,NaN
d,0.847829,0.057048,0.914986,0.625122,84.782889,1.762815,Kolkata,Kolkata,NaN
e,0.954197,0.168059,0.364463,0.153924,95.419671,1.318660,Bengaluru,Bengaluru,Bengaluru
f,0.454947,0.104159,0.427967,0.338639,45.494690,0.882914,Hydrabad,Hydrabad,NaN
g,0.464129,0.183931,0.733576,0.975621,46.412931,1.197706,Pune,Pune,NaN
h,0.000000,0.202819,0.443558,0.160414,9.755311,0.541111,Ahmedabad,Ahmedabad,NaN
i,0.683309,0.504838,0.434979,0.332304,68.330887,1.118288,Indore,Guwahati,NaN

In [456]:
df_copy.drop(["new_cities"],axis=1)

,A,B,C,D,E,F,city,new_city
a,0.897615,0.458515,0.918921,0.259367,89.761497,1.816536,mumbai,mumbai
b,0.404996,0.489543,0.719259,0.391869,40.499620,1.124255,Delhi,Delhi
c,0.202180,0.036154,0.457360,0.535389,20.217969,0.659540,Chennai,Chennai
d,0.847829,0.057048,0.914986,0.625122,84.782889,1.762815,Kolkata,Kolkata
e,0.954197,0.168059,0.364463,0.153924,95.419671,1.318660,Bengaluru,Bengaluru
f,0.454947,0.104159,0.427967,0.338639,45.494690,0.882914,Hydrabad,Hydrabad
g,0.464129,0.183931,0.733576,0.975621,46.412931,1.197706,Pune,Pune
h,0.000000,0.202819,0.443558,0.160414,9.755311,0.541111,Ahmedabad,Ahmedabad
i,0.683309,0.504838,0.434979,0.332304,68.330887,1.118288,Indore,Guwahati

In [457]:
criteria

a    False
b    False
c    False
d    False
e    False
f     True
g     True
h    False
i    False
Name: city, dtype: bool

In [458]:
df_copy.loc[:,"city"]="Chennai"

In [459]:
df_copy

,A,B,C,D,E,F,city,new_city,new_cities
a,0.897615,0.458515,0.918921,0.259367,89.761497,1.816536,Chennai,mumbai,NaN
b,0.404996,0.489543,0.719259,0.391869,40.499620,1.124255,Chennai,Delhi,NaN
c,0.202180,0.036154,0.457360,0.535389,20.217969,0.659540,Chennai,Chennai,NaN
d,0.847829,0.057048,0.914986,0.625122,84.782889,1.762815,Chennai,Kolkata,NaN
e,0.954197,0.168059,0.364463,0.153924,95.419671,1.318660,Chennai,Bengaluru,Bengaluru
f,0.454947,0.104159,0.427967,0.338639,45.494690,0.882914,Chennai,Hydrabad,NaN
g,0.464129,0.183931,0.733576,0.975621,46.412931,1.197706,Chennai,Pune,NaN
h,0.000000,0.202819,0.443558,0.160414,9.755311,0.541111,Chennai,Ahmedabad,NaN
i,0.683309,0.504838,0.434979,0.332304,68.330887,1.118288,Chennai,Guwahati,NaN

In [460]:
df_copy=df_copy.drop(["new_cities"],axis=1)

In [461]:
df_copy

,A,B,C,D,E,F,city,new_city
a,0.897615,0.458515,0.918921,0.259367,89.761497,1.816536,Chennai,mumbai
b,0.404996,0.489543,0.719259,0.391869,40.499620,1.124255,Chennai,Delhi
c,0.202180,0.036154,0.457360,0.535389,20.217969,0.659540,Chennai,Chennai
d,0.847829,0.057048,0.914986,0.625122,84.782889,1.762815,Chennai,Kolkata
e,0.954197,0.168059,0.364463,0.153924,95.419671,1.318660,Chennai,Bengaluru
f,0.454947,0.104159,0.427967,0.338639,45.494690,0.882914,Chennai,Hydrabad
g,0.464129,0.183931,0.733576,0.975621,46.412931,1.197706,Chennai,Pune
h,0.000000,0.202819,0.443558,0.160414,9.755311,0.541111,Chennai,Ahmedabad
i,0.683309,0.504838,0.434979,0.332304,68.330887,1.118288,Chennai,Guwahati

In [462]:
?df_copy.sample

Signature:
df_copy.sample(
    n: 'int | None' = None,
    frac: 'float | None' = None,
    replace: 'bool_t' = False,
    weights=None,
    random_state: 'RandomState | None' = None,
    axis: 'Axis | None' = None,
    ignore_index: 'bool_t' = False,
) -> 'Self'
Docstring:
Return a random sample of items from an axis of object.

You can use `random_state` for reproducibility.

Parameters
----------
n : int, optional
    Number of items from axis to return. Cannot be used with `frac`.
    Default = 1 if `frac` = None.
frac : float, optional
    Fraction of axis items to return. Cannot be used with `n`.
replace : bool, default False
    Allow or disallow sampling of the same row more than once.
weights : str or ndarray-like, optional
    Default 'None' results in equal probability weighting.
    If passed a Series, will align with target object on index. Index
    values in weights not found in sampled object will be ignored and
    index values in sampled object not in weights will be assigned
    weights of zero.
    If called on a DataFrame, will accept the name of a column
    when axis = 0.
    Unless weights are a Series, weights must be same length as axis
    being sampled.
    If weights do not sum to 1, they will be normalized to sum to 1.
    Missing values in the weights column will be treated as zero.
    Infinite values not allowed.
random_state : int, array-like, BitGenerator, np.random.RandomState, np.random.Generator, optional
    If int, array-like, or BitGenerator, seed for random number generator.
    If np.random.RandomState or np.random.Generator, use as given.

    .. versionchanged:: 1.4.0

        np.random.Generator objects now accepted

axis : {0 or 'index', 1 or 'columns', None}, default None
    Axis to sample. Accepts axis number or name. Default is stat axis
    for given data type. For `Series` this parameter is unused and defaults to `None`.
ignore_index : bool, default False
    If True, the resulting index will be labeled 0, 1, …, n - 1.

    .. versionadded:: 1.3.0

Returns
-------
Series or DataFrame
    A new object of same type as caller containing `n` items randomly
    sampled from the caller object.

See Also
--------
DataFrameGroupBy.sample: Generates random samples from each group of a
    DataFrame object.
SeriesGroupBy.sample: Generates random samples from each group of a
    Series object.
numpy.random.choice: Generates a random sample from a given 1-D numpy
    array.

Notes
-----
If `frac` > 1, `replacement` should be set to `True`.

Examples
--------
>>> df = pd.DataFrame({'num_legs': [2, 4, 8, 0],
...                    'num_wings': [2, 0, 0, 0],
...                    'num_specimen_seen': [10, 2, 1, 8]},
...                   index=['falcon', 'dog', 'spider', 'fish'])
>>> df
        num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8

Extract 3 random elements from the ``Series`` ``df['num_legs']``:
Note that we use `random_state` to ensure the reproducibility of
the examples.

>>> df['num_legs'].sample(n=3, random_state=1)
fish      0
spider    8
falcon    2
Name: num_legs, dtype: int64

A random 50% sample of the ``DataFrame`` with replacement:

>>> df.sample(frac=0.5, replace=True, random_state=1)
      num_legs  num_wings  num_specimen_seen
dog          4          0                  2
fish         0          0                  8

An upsample sample of the ``DataFrame`` with replacement:
Note that `replace` parameter has to be `True` for `frac` parameter > 1.

>>> df.sample(frac=2, replace=True, random_state=1)
        num_legs  num_wings  num_specimen_seen
dog            4          0                  2
fish           0          0                  8
falcon         2          2                 10
falcon         2          2                 10
fish           0          0                  8
dog            4          0                  2
fish           0          0                  8
dog            4          0                  2

Using a DataFrame column as weights. Rows with larger value in the
`num_specimen_seen` column are more likely to be sampled.

>>> df.sample(n=2, weights='num_specimen_seen', random_state=1)
        num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
fish           0          0                  8
File:      d:\anaconda\envs\enev\lib\site-packages\pandas\core\generic.py
Type:      method

In [464]:
df_copy.sample(5)

,A,B,C,D,E,F,city,new_city
d,0.847829,0.057048,0.914986,0.625122,84.782889,1.762815,Chennai,Kolkata
e,0.954197,0.168059,0.364463,0.153924,95.419671,1.318660,Chennai,Bengaluru
f,0.454947,0.104159,0.427967,0.338639,45.494690,0.882914,Chennai,Hydrabad
a,0.897615,0.458515,0.918921,0.259367,89.761497,1.816536,Chennai,mumbai
c,0.202180,0.036154,0.457360,0.535389,20.217969,0.659540,Chennai,Chennai

In [472]:
df_copy.sample(3,random_state=42)

,A,B,C,D,E,F,city,new_city
h,0.000000,0.202819,0.443558,0.160414,9.755311,0.541111,Chennai,Ahmedabad
b,0.404996,0.489543,0.719259,0.391869,40.499620,1.124255,Chennai,Delhi
f,0.454947,0.104159,0.427967,0.338639,45.494690,0.882914,Chennai,Hydrabad

In [470]:
df_copy.sample(3,random_state=42)

,A,B,C,D,E,F,city,new_city
h,0.000000,0.202819,0.443558,0.160414,9.755311,0.541111,Chennai,Ahmedabad
b,0.404996,0.489543,0.719259,0.391869,40.499620,1.124255,Chennai,Delhi
f,0.454947,0.104159,0.427967,0.338639,45.494690,0.882914,Chennai,Hydrabad

In [471]:
df_copy.sample(3,random_state=42,replace=True)

,A,B,C,D,E,F,city,new_city
g,0.464129,0.183931,0.733576,0.975621,46.412931,1.197706,Chennai,Pune
d,0.847829,0.057048,0.914986,0.625122,84.782889,1.762815,Chennai,Kolkata
h,0.000000,0.202819,0.443558,0.160414,9.755311,0.541111,Chennai,Ahmedabad